FROM registry.fedoraproject.org/fedora-toolbox:36

# OS REFRESH & CLI

ARG PWSH_VERSION

RUN dnf upgrade -y \
    && dnf install -y gh \
    && dnf install -y https://github.com/PowerShell/PowerShell/releases/download/v${PWSH_VERSION}/powershell-${PWSH_VERSION}-1.rh.x86_64.rpm \
    && dnf clean all

# python -> create a symlink if it doesn't exist yet
RUN [ ! -f /usr/bin/python ] && ln -s ./python3 /usr/bin/python

# NODE

ARG NODE_VERSION
ENV NODE_VERSION=${NODE_VERSION}
ENV NODE_DISTRO linux-x64

RUN set -ex \
    # gpg keys listed at https://github.com/nodejs/node#release-keys
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 4ED778F539E3634C779C87C6D7062848A1AB005C \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 74F12602B6F1C4E913FAA37AD3A89613643B6201 \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A48C2BEE680E841632CD4E44F07496B3EB3C1762 \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 108F52B48DB57BB0CC439B2997B01419BD92F80A \
    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys B9E2F5981AA6E0CD28160D9FF13993A75599653C \
    # download
    && curl -fsSLO --compressed "https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-${NODE_DISTRO}.tar.xz" \
    && curl -fsSLO --compressed "https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt.asc" \
    # verify
    && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
    && grep " node-${NODE_VERSION}-${NODE_DISTRO}.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
    # unpack
    && mkdir -p /usr/local/lib/nodejs \
    && tar -xJf "node-${NODE_VERSION}-${NODE_DISTRO}.tar.xz" -C /usr/local/lib/nodejs --strip-components=1 --no-same-owner \
    && rm "node-${NODE_VERSION}-${NODE_DISTRO}.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt

ENV PATH "/usr/local/lib/nodejs/bin:$PATH"
RUN corepack enable

# CUSTOMIZATION

WORKDIR /src
COPY ./src .
RUN \
    ## bash
    cat .bashrc >> /root/.bashrc \
    ## git
    && cp .gitconfig /root \
    ## powershell
    && mkdir -p /root/.config/powershell \
    && cp profile.ps1 /root/.config/powershell \
    ## wsl
    && cp wsl.conf /etc

WORKDIR /
RUN rm -rf /src

# END

WORKDIR /
CMD [ "bash" ]
